# Use the official Golang image as the base image
FROM golang:1.25.3-alpine
# Set the Current Working Directory inside the container
WORKDIR /app
# Copy go.mod and go.sum files
COPY go.mod ./
# Install dependencies
RUN go mod download
# # Copy .env file
# COPY .env ./
# Copy the source code
COPY . .
# Build the Go app
RUN go build -o ./cms-practice-api .
# Expose port 8081 to the outside world
EXPOSE 8080
# Command to run the executable
CMD ["./cms-practice-api"]
